FROM python:3.9.20-slim-bookworm AS build.trufflehog
RUN apt update && apt install -y git && \
    pip install truffleHog && \
    git config --global --add safe.directory /app && \
    mkdir -p /app/trufflehog_reports
WORKDIR /app
COPY . .

# Define the command to run TruffleHog
CMD ["sh", "-c", "trufflehog --repo_path . --json https://github.com/carl-geralz/Booking-room > /app/trufflehog_reports/trufflehog_report.json"]
